/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;


import Model.JogoIRL;
import Model.JogoSimulation;
import Model.Player;
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

public class PainelCampeao extends javax.swing.JPanel {
    JogoSimulation jogoSimulation = null;
    JogoIRL jogoIRL = null;
    Player campeao = null;

    public PainelCampeao(Player campeao,JogoSimulation jogoSimulation, JogoIRL jogoIRL) {
        initComponents();
        this.jogoIRL = jogoIRL;
        this.jogoSimulation = jogoSimulation;
        this.campeao = campeao;
        ajustes();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        la_nome = new javax.swing.JLabel();
        la_eOCampeao = new javax.swing.JLabel();
        la_finalEstatica = new javax.swing.JLabel();
        la_finalDinamica = new javax.swing.JLabel();
        la_time = new javax.swing.JLabel();
        la_dominou = new javax.swing.JLabel();
        bt_continuar = new javax.swing.JButton();
        bt_visualizar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        la_nome.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        la_nome.setForeground(new java.awt.Color(255, 0, 0));
        la_nome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        la_nome.setText("<NOME_PLAYER>");
        add(la_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 80));

        la_eOCampeao.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        la_eOCampeao.setForeground(new java.awt.Color(255, 0, 0));
        la_eOCampeao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        la_eOCampeao.setText("É O GRANDE CAMPEÃO!!!");
        add(la_eOCampeao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 80));

        la_finalEstatica.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        la_finalEstatica.setForeground(new java.awt.Color(255, 0, 0));
        la_finalEstatica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        la_finalEstatica.setText("FINAL:");
        add(la_finalEstatica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 630, 80));

        la_finalDinamica.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        la_finalDinamica.setForeground(new java.awt.Color(255, 0, 0));
        la_finalDinamica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        la_finalDinamica.setText("FINAL");
        add(la_finalDinamica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 630, 80));

        la_time.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        la_time.setForeground(new java.awt.Color(255, 0, 0));
        la_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        la_time.setText("<TMn>");
        add(la_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 80));

        la_dominou.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        la_dominou.setForeground(new java.awt.Color(255, 0, 0));
        la_dominou.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        la_dominou.setText("DOMINOU A COMPETIÇÃO!!!!");
        add(la_dominou, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 560, 80));

        bt_continuar.setBackground(new java.awt.Color(51, 51, 51));
        bt_continuar.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        bt_continuar.setForeground(new java.awt.Color(255, 0, 0));
        bt_continuar.setText("CONTINUAR");
        bt_continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_continuar.setFocusPainted(false);
        bt_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_continuarActionPerformed(evt);
            }
        });
        add(bt_continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 190, 90));

        bt_visualizar.setBackground(new java.awt.Color(51, 51, 51));
        bt_visualizar.setFont(new java.awt.Font("Stencil", 3, 18)); // NOI18N
        bt_visualizar.setForeground(new java.awt.Color(255, 0, 0));
        bt_visualizar.setText("VISUALIZAR LIGA");
        bt_visualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_visualizar.setFocusPainted(false);
        bt_visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_visualizarActionPerformed(evt);
            }
        });
        add(bt_visualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 190, 90));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/telaCampeao700x500.png"))); // NOI18N
        add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void exibePlacarFinal(){
        if(Janela.controller.getModoDeJogo().equalsIgnoreCase("simulacao")){
            String tm0 = jogoSimulation.getListaPlayersFinal().get(0).getTime();
            String gol0 = String.valueOf(jogoSimulation.getListaPlayersFinal().get(0).getGol2());
            String tm1 = String.valueOf(jogoSimulation.getListaPlayersFinal().get(1).getTime());
            String gol1 = String.valueOf(jogoSimulation.getListaPlayersFinal().get(1).getGol2());
            
            String finalissima = (tm0 +" "+ gol0 +  " x " + gol1 +" "+ tm1);
            //lembrando que final é palavra reservada
            
            la_finalDinamica.setText(finalissima);
        }
        
        if(Janela.controller.getModoDeJogo().equalsIgnoreCase("irl")){
            String tm0 = jogoIRL.getListaPlayersFinal().get(0).getTime();
            String gol0 = String.valueOf(jogoIRL.getListaPlayersFinal().get(0).getGol2());
            String tm1 = String.valueOf(jogoIRL.getListaPlayersFinal().get(1).getTime());
            String gol1 = String.valueOf(jogoIRL.getListaPlayersFinal().get(1).getGol2());
            
            String finalissima = (tm0 +" "+ gol0 +  " x " + gol1 +" "+ tm1);
            //lembrando que final é palavra reservada
            
            la_finalDinamica.setText(finalissima);
        }
    }
    
    
    private void bt_visualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_visualizarActionPerformed
        Janela.painelConfrontos = new PainelConfrontos(jogoSimulation, jogoIRL);
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(Janela.painelCampeao);
        janela.add(Janela.painelConfrontos, BorderLayout.CENTER);
        janela.pack();
    }//GEN-LAST:event_bt_visualizarActionPerformed

    private void bt_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_continuarActionPerformed
        Janela.painelHome = new PainelHome();
        JFrame janela = (JFrame) SwingUtilities.getWindowAncestor(this);
        janela.getContentPane().remove(Janela.painelCampeao);
        janela.add(Janela.painelHome, BorderLayout.CENTER);
        janela.pack();
    }//GEN-LAST:event_bt_continuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton bt_continuar;
    private javax.swing.JButton bt_visualizar;
    private javax.swing.JLabel la_dominou;
    private javax.swing.JLabel la_eOCampeao;
    private javax.swing.JLabel la_finalDinamica;
    private javax.swing.JLabel la_finalEstatica;
    private javax.swing.JLabel la_nome;
    private javax.swing.JLabel la_time;
    // End of variables declaration//GEN-END:variables

    private void ajustes() {
        la_nome.setText(campeao.getNome());
        la_time.setText(campeao.getTime());
        exibePlacarFinal();
    }
}
